### PR TITLE
s22-5pm-1 format enrollment

### LINKED ISSUE #66: Format Enrollment on SectionsTable
- [x] Create a utility function to format `enrolledTotal` and `enrollMax` as a fraction
- [x] Display percentage based on the total and Max
- [x] Pass all tests

### PR DESCRIPTION
**Pull request by alexward120**
Added the enrollment column to display in a nice fraction rather than seperate column. Enroll code added as I felt it was important.
image

Test Plan:
* Click on section search

* Search for a random section by choosing any quarter, courseCode, and courseLevel.

* The Enrollment column should show a fraction of the total enrolled over the max seats available and give a percentage.

* Some rows will return empty as either total enrolled or max seats are null.

* Some rows will have a single number(total seats)  if max seats is not null and total enrolled is null
Nan/Nan (Nan%) shouldn't appear for any of the rows.

* Enroll Code Column should be visible with codes for each column.

### CODE REVIEW

**Review by chrisstasiowski01 — DISMISSED** [review]
LGTM!

**Review by chrisstasiowski01 — DISMISSED** [review]
LGTM!

**Review by chrisstasiowski01 — APPROVED** [review]
LGTM!

**Review by pconrad — APPROVED** [review]
LGTM!  Will test on QA

**Pull request merged**
