### PR TITLE
S22-5pm-2 RV - Add API endpoint for getting section information from a schedule

### PR DESCRIPTION
**Pull request by jacksonjude**
# Overview

In this PR, I added an API that takes in a PersonalSchedule object id and returns a list of all the schedules within that schedule. 
I also added tests for ScheduleSectionController

addresses #11 

# Testing Plan using [Swagger](https://s22-5pm-2-courses-qa.herokuapp.com/swagger-ui/index.html#/)
- Create a personal schedule (with the __/api/personalschedules/post__ endpoint) if you don't already have one. Take note of the psId and the quarter
- In another window, get a few valid enrollCd's for that quarter.
- In Swagger, use the __/api/addedcourses/post__ endpoint to add a few courses to that personal schedule
- Go to the __/api/addedcourses__ endpoint and enter the psId. You should see JSON that has section information about each of the enrollCds on the personal schedule.

### CODE REVIEW

**Review by pconrad — DISMISSED** [review]
LGTM... but will test on QA.

I see a few things that I want to make sure actually work...

**Review by hyunkyumkim — DISMISSED** [review]
LGTM

**Review by pconrad — DISMISSED** [review]
LGTM.. will test on QA

**Review by ryanlavu — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
