### PR TITLE
s22-5pm-2 - Added details button to Personal Schedule Table + tests

### LINKED ISSUE #42: Add frontend component that routes to Personal Schedule Details Page
# Acceptance Critera

- [x] A button titled "Details" properly renders for each personal schedule, for both admin and ordinary users
- [x] The "Details" button properly routes to the Details placeholder page for each personal schedule 
- [x] Passes CI/CD

### PR DESCRIPTION
**Pull request by jaoviedo**
# Overview

This PR gives the any user, admin or not, to route to the placeholder details page for each personal schedule from the personal schedule index page through a "Details" button on its own column.

# Issues Addressed
Closes #42 

# Testing Plan ([QA](https://s22-5pm-2-courses-qa.herokuapp.com))
- Log into the site and create a new personal schedule (at /personalschedules/create) if one does not exist yet
- In the personal schedule list, verify that there is a "Details" column containing "Details" buttons
- Click the "Details" button for a personal schedule and verify that it sends you to a placeholder page where the psId is displayed

Screen Shot 2022-06-05 at 11 18 11 PM

Screen Shot 2022-06-05 at 11 18 56 PM

### CODE REVIEW

**Review by hyunkyumkim — DISMISSED** [review]
LGTM

**Review by anouki-p — DISMISSED** [review]
lgtm

**Review by jacksonjude — DISMISSED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
Assuming the page it's routing to exists, and that it works on QA:

LGTM.. but I will test it before merging.

**Review by hyunkyumkim — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
