### PR TITLE
s22-5pm-1 RP - Added new component that renders a course table with section info

### LINKED ISSUE #21: Add new component that renders a course table with section info.
Note: Assume that the data passed to the component called sections is a list of javascript objects, in the same format that is agreed on that the new API endpoint will return.

# Acceptance Criteria
- [X] A `Section` component containing a file implementing the table exists.
- [X] Fixtures for the table are utilized for testing purposes
- [X] Storybook displays all required fields effectively.
- [X] 100% Test Coverage
- [X] 100% Mutation Coverage

### PR DESCRIPTION
**Pull request by rishabhpoikayil**
In this PR, a table displaying important fields in relation to section for courses was implemented as shown below. This table will be integrated into the section search index page, which will allow users to find information regarding all sections for a particular course.

image

This PR achieved full mutation coverage and test coverage. 

image

image

The fields are displayed as intended, proof of which can be seen in Storybook.
image

#21

### CODE REVIEW

**Review by alexward120 — DISMISSED** [review]
LGTM!

**Review by JoejoeWang — DISMISSED** [review]
nice job

**Review by alexward120 — APPROVED** [review]
LGTM

**Review by alexward120 — APPROVED** [review]
LGTM

**Review by alexward120 — DISMISSED** [review]
LGTM

**Review by JoejoeWang — DISMISSED** [review]
looks good

**Review by alexward120 — APPROVED** [review]
LGTM

**Pull request closed without merging**
