### PR TITLE
5pm-2 hkk - added Heroku production app and dashboard links to README.md & set up Google OAuth

### LINKED ISSUE #3: Add `Heroku production app` and `dashboard` links to `README.md`
Add `Heroku production app` and `dashboard` links to `README.md`

# Acceptance Criteria:

- [x] Create `Heroku production app`
- [x] Add `Heroku production app` link to `README.md`
- [x] Add `Heroku production app dashboard` link to `README.md`
- [x] Pass checks

### LINKED ISSUE #4: Set up OAuth credentials that work on http://localhost:8080 as well as on your Heroku production deployment
Set up OAuth credentials that work on http://localhost:8080 as well as on your Heroku production deployment

# Acceptance Criteria

- [x] Create Google OAuth credentials
- [x] Test Google OAuth credentials on localhost:8080
- [x] Test Google OAuth credentials on Heroku production app
- [x] Pass checks

### PR DESCRIPTION
**Pull request by hyunkyumkim**
# Overview

In this PR,

1. Add Heroku production app link to README.md
2. Add Heroku production app dashboard link to README.md
3. a) Set up Google OAuth credentials that work on `http://localhost:8080`
3. b) ... that work on `Heroku production deployment`

# Issues Addressed

Closes #3 
Closes #4

### CODE REVIEW

**Review by pconrad — CHANGES_REQUESTED** [review]
The code change looks fine, but it appears you haven't given access to the staff to this heroku deployment.  Note this in the instructions:

> Add all of the staff to the production deployment: alu@ucsb.edu, kheffernan@ucsb.edu, bzamoraflores@ucsb.edu, andrewpeng@ucsb.edu, phtcon@ucsb.edu.

**Review by liminding-UCSB — DISMISSED** [review]
LGTM

**Review by andrewpengucsb — DISMISSED** [review]
LGTM!

**Review by jacksonjude — DISMISSED** [review]
LGTM

**Review by pconrad — APPROVED** [review]

**Comment by pconrad** [comment]
10 pts when merged, because also includes OAuth setup.

**Review by jacksonjude — APPROVED** [review]
LGTM

**Pull request merged**
