### PR TITLE
s22-5pm-1 cs - changed app title and added calendar favicon

### LINKED ISSUE #48: Change application title and add favicon that fits the app.
- [x] when visiting web app in browser, favicon is displayed at top in current tab
- [x] web app has title that displays in tab (i.e. not "React App"

### PR DESCRIPTION
**Pull request by chrisstasiowski01**
This PR adds a calendar favicon that displays in the user's current tab in their browser. There is also a title ("UCSB Courses Search") that displays in the tab that replaces "React App".

Screen Shot 2022-06-01 at 5 43 31 PM

Closes #48

### CODE REVIEW

**Review by jonahparkucsb — DISMISSED** [review]

**Review by pconrad — CHANGES_REQUESTED** [review]
It's not ok to delete .env.SAMPLE

Please restore this file; this PR isn't mergeable until that's restored.

**Review by pconrad — APPROVED** [review]
LGTM

**Review by pconrad — CHANGES_REQUESTED** [review]
Need to restore the .env.SAMPLE
or this isn't mergeable.

**Review by nthnga13 — DISMISSED** [review]
Looks good LGTM

**Review by alexward120 — DISMISSED** [review]
LGTM

**Review by alexward120 — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM.   Probably should have changed the "brand" on the navbar too..

**Pull request merged**
